// Code generated by ent, DO NOT EDIT.

package redeemcampaignredemption

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the redeemcampaignredemption type in the database.
	Label = "redeem_campaign_redemption"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCampaignID holds the string denoting the campaign_id field in the database.
	FieldCampaignID = "campaign_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldRedeemCodeID holds the string denoting the redeem_code_id field in the database.
	FieldRedeemCodeID = "redeem_code_id"
	// FieldRedeemedAt holds the string denoting the redeemed_at field in the database.
	FieldRedeemedAt = "redeemed_at"
	// Table holds the table name of the redeemcampaignredemption in the database.
	Table = "redeem_campaign_redemptions"
)

// Columns holds all SQL columns for redeemcampaignredemption fields.
var Columns = []string{
	FieldID,
	FieldCampaignID,
	FieldUserID,
	FieldRedeemCodeID,
	FieldRedeemedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRedeemedAt holds the default value on creation for the "redeemed_at" field.
	DefaultRedeemedAt func() time.Time
)

// OrderOption defines the ordering options for the RedeemCampaignRedemption queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCampaignID orders the results by the campaign_id field.
func ByCampaignID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCampaignID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByRedeemCodeID orders the results by the redeem_code_id field.
func ByRedeemCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemCodeID, opts...).ToFunc()
}

// ByRedeemedAt orders the results by the redeemed_at field.
func ByRedeemedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedAt, opts...).ToFunc()
}
