// Code generated by ent, DO NOT EDIT.

package redeemcampaignredemption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLTE(FieldID, id))
}

// CampaignID applies equality check predicate on the "campaign_id" field. It's identical to CampaignIDEQ.
func CampaignID(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldCampaignID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldUserID, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemedAt applies equality check predicate on the "redeemed_at" field. It's identical to RedeemedAtEQ.
func RedeemedAt(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldRedeemedAt, v))
}

// CampaignIDEQ applies the EQ predicate on the "campaign_id" field.
func CampaignIDEQ(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldCampaignID, v))
}

// CampaignIDNEQ applies the NEQ predicate on the "campaign_id" field.
func CampaignIDNEQ(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNEQ(FieldCampaignID, v))
}

// CampaignIDIn applies the In predicate on the "campaign_id" field.
func CampaignIDIn(vs ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldIn(FieldCampaignID, vs...))
}

// CampaignIDNotIn applies the NotIn predicate on the "campaign_id" field.
func CampaignIDNotIn(vs ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNotIn(FieldCampaignID, vs...))
}

// CampaignIDGT applies the GT predicate on the "campaign_id" field.
func CampaignIDGT(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGT(FieldCampaignID, v))
}

// CampaignIDGTE applies the GTE predicate on the "campaign_id" field.
func CampaignIDGTE(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGTE(FieldCampaignID, v))
}

// CampaignIDLT applies the LT predicate on the "campaign_id" field.
func CampaignIDLT(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLT(FieldCampaignID, v))
}

// CampaignIDLTE applies the LTE predicate on the "campaign_id" field.
func CampaignIDLTE(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLTE(FieldCampaignID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLTE(FieldUserID, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int64) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDIsNil applies the IsNil predicate on the "redeem_code_id" field.
func RedeemCodeIDIsNil() predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldIsNull(FieldRedeemCodeID))
}

// RedeemCodeIDNotNil applies the NotNil predicate on the "redeem_code_id" field.
func RedeemCodeIDNotNil() predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNotNull(FieldRedeemCodeID))
}

// RedeemedAtEQ applies the EQ predicate on the "redeemed_at" field.
func RedeemedAtEQ(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldEQ(FieldRedeemedAt, v))
}

// RedeemedAtNEQ applies the NEQ predicate on the "redeemed_at" field.
func RedeemedAtNEQ(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNEQ(FieldRedeemedAt, v))
}

// RedeemedAtIn applies the In predicate on the "redeemed_at" field.
func RedeemedAtIn(vs ...time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldIn(FieldRedeemedAt, vs...))
}

// RedeemedAtNotIn applies the NotIn predicate on the "redeemed_at" field.
func RedeemedAtNotIn(vs ...time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldNotIn(FieldRedeemedAt, vs...))
}

// RedeemedAtGT applies the GT predicate on the "redeemed_at" field.
func RedeemedAtGT(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGT(FieldRedeemedAt, v))
}

// RedeemedAtGTE applies the GTE predicate on the "redeemed_at" field.
func RedeemedAtGTE(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldGTE(FieldRedeemedAt, v))
}

// RedeemedAtLT applies the LT predicate on the "redeemed_at" field.
func RedeemedAtLT(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLT(FieldRedeemedAt, v))
}

// RedeemedAtLTE applies the LTE predicate on the "redeemed_at" field.
func RedeemedAtLTE(v time.Time) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.FieldLTE(FieldRedeemedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedeemCampaignRedemption) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedeemCampaignRedemption) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedeemCampaignRedemption) predicate.RedeemCampaignRedemption {
	return predicate.RedeemCampaignRedemption(sql.NotPredicates(p))
}
