// Code generated by ent, DO NOT EDIT.

package supportticket

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldTitle, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCategory, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldStatus, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldPriority, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastUserMessageAt applies equality check predicate on the "last_user_message_at" field. It's identical to LastUserMessageAtEQ.
func LastUserMessageAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastUserMessageAt, v))
}

// LastAdminMessageAt applies equality check predicate on the "last_admin_message_at" field. It's identical to LastAdminMessageAtEQ.
func LastAdminMessageAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastAdminMessageAt, v))
}

// UserLastReadAt applies equality check predicate on the "user_last_read_at" field. It's identical to UserLastReadAtEQ.
func UserLastReadAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUserLastReadAt, v))
}

// AdminLastReadAt applies equality check predicate on the "admin_last_read_at" field. It's identical to AdminLastReadAtEQ.
func AdminLastReadAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAdminLastReadAt, v))
}

// AssignedAdminID applies equality check predicate on the "assigned_admin_id" field. It's identical to AssignedAdminIDEQ.
func AssignedAdminID(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAssignedAdminID, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedBy applies equality check predicate on the "closed_by" field. It's identical to ClosedByEQ.
func ClosedBy(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldClosedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldUserID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldTitle, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldCategory, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldStatus, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldContainsFold(FieldPriority, v))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldLastMessageAt, v))
}

// LastMessageAtIsNil applies the IsNil predicate on the "last_message_at" field.
func LastMessageAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldLastMessageAt))
}

// LastMessageAtNotNil applies the NotNil predicate on the "last_message_at" field.
func LastMessageAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldLastMessageAt))
}

// LastUserMessageAtEQ applies the EQ predicate on the "last_user_message_at" field.
func LastUserMessageAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastUserMessageAt, v))
}

// LastUserMessageAtNEQ applies the NEQ predicate on the "last_user_message_at" field.
func LastUserMessageAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldLastUserMessageAt, v))
}

// LastUserMessageAtIn applies the In predicate on the "last_user_message_at" field.
func LastUserMessageAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldLastUserMessageAt, vs...))
}

// LastUserMessageAtNotIn applies the NotIn predicate on the "last_user_message_at" field.
func LastUserMessageAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldLastUserMessageAt, vs...))
}

// LastUserMessageAtGT applies the GT predicate on the "last_user_message_at" field.
func LastUserMessageAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldLastUserMessageAt, v))
}

// LastUserMessageAtGTE applies the GTE predicate on the "last_user_message_at" field.
func LastUserMessageAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldLastUserMessageAt, v))
}

// LastUserMessageAtLT applies the LT predicate on the "last_user_message_at" field.
func LastUserMessageAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldLastUserMessageAt, v))
}

// LastUserMessageAtLTE applies the LTE predicate on the "last_user_message_at" field.
func LastUserMessageAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldLastUserMessageAt, v))
}

// LastUserMessageAtIsNil applies the IsNil predicate on the "last_user_message_at" field.
func LastUserMessageAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldLastUserMessageAt))
}

// LastUserMessageAtNotNil applies the NotNil predicate on the "last_user_message_at" field.
func LastUserMessageAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldLastUserMessageAt))
}

// LastAdminMessageAtEQ applies the EQ predicate on the "last_admin_message_at" field.
func LastAdminMessageAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtNEQ applies the NEQ predicate on the "last_admin_message_at" field.
func LastAdminMessageAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtIn applies the In predicate on the "last_admin_message_at" field.
func LastAdminMessageAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldLastAdminMessageAt, vs...))
}

// LastAdminMessageAtNotIn applies the NotIn predicate on the "last_admin_message_at" field.
func LastAdminMessageAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldLastAdminMessageAt, vs...))
}

// LastAdminMessageAtGT applies the GT predicate on the "last_admin_message_at" field.
func LastAdminMessageAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtGTE applies the GTE predicate on the "last_admin_message_at" field.
func LastAdminMessageAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtLT applies the LT predicate on the "last_admin_message_at" field.
func LastAdminMessageAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtLTE applies the LTE predicate on the "last_admin_message_at" field.
func LastAdminMessageAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldLastAdminMessageAt, v))
}

// LastAdminMessageAtIsNil applies the IsNil predicate on the "last_admin_message_at" field.
func LastAdminMessageAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldLastAdminMessageAt))
}

// LastAdminMessageAtNotNil applies the NotNil predicate on the "last_admin_message_at" field.
func LastAdminMessageAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldLastAdminMessageAt))
}

// UserLastReadAtEQ applies the EQ predicate on the "user_last_read_at" field.
func UserLastReadAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUserLastReadAt, v))
}

// UserLastReadAtNEQ applies the NEQ predicate on the "user_last_read_at" field.
func UserLastReadAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldUserLastReadAt, v))
}

// UserLastReadAtIn applies the In predicate on the "user_last_read_at" field.
func UserLastReadAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldUserLastReadAt, vs...))
}

// UserLastReadAtNotIn applies the NotIn predicate on the "user_last_read_at" field.
func UserLastReadAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldUserLastReadAt, vs...))
}

// UserLastReadAtGT applies the GT predicate on the "user_last_read_at" field.
func UserLastReadAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldUserLastReadAt, v))
}

// UserLastReadAtGTE applies the GTE predicate on the "user_last_read_at" field.
func UserLastReadAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldUserLastReadAt, v))
}

// UserLastReadAtLT applies the LT predicate on the "user_last_read_at" field.
func UserLastReadAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldUserLastReadAt, v))
}

// UserLastReadAtLTE applies the LTE predicate on the "user_last_read_at" field.
func UserLastReadAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldUserLastReadAt, v))
}

// UserLastReadAtIsNil applies the IsNil predicate on the "user_last_read_at" field.
func UserLastReadAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldUserLastReadAt))
}

// UserLastReadAtNotNil applies the NotNil predicate on the "user_last_read_at" field.
func UserLastReadAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldUserLastReadAt))
}

// AdminLastReadAtEQ applies the EQ predicate on the "admin_last_read_at" field.
func AdminLastReadAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAdminLastReadAt, v))
}

// AdminLastReadAtNEQ applies the NEQ predicate on the "admin_last_read_at" field.
func AdminLastReadAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldAdminLastReadAt, v))
}

// AdminLastReadAtIn applies the In predicate on the "admin_last_read_at" field.
func AdminLastReadAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldAdminLastReadAt, vs...))
}

// AdminLastReadAtNotIn applies the NotIn predicate on the "admin_last_read_at" field.
func AdminLastReadAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldAdminLastReadAt, vs...))
}

// AdminLastReadAtGT applies the GT predicate on the "admin_last_read_at" field.
func AdminLastReadAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldAdminLastReadAt, v))
}

// AdminLastReadAtGTE applies the GTE predicate on the "admin_last_read_at" field.
func AdminLastReadAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldAdminLastReadAt, v))
}

// AdminLastReadAtLT applies the LT predicate on the "admin_last_read_at" field.
func AdminLastReadAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldAdminLastReadAt, v))
}

// AdminLastReadAtLTE applies the LTE predicate on the "admin_last_read_at" field.
func AdminLastReadAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldAdminLastReadAt, v))
}

// AdminLastReadAtIsNil applies the IsNil predicate on the "admin_last_read_at" field.
func AdminLastReadAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldAdminLastReadAt))
}

// AdminLastReadAtNotNil applies the NotNil predicate on the "admin_last_read_at" field.
func AdminLastReadAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldAdminLastReadAt))
}

// AssignedAdminIDEQ applies the EQ predicate on the "assigned_admin_id" field.
func AssignedAdminIDEQ(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldAssignedAdminID, v))
}

// AssignedAdminIDNEQ applies the NEQ predicate on the "assigned_admin_id" field.
func AssignedAdminIDNEQ(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldAssignedAdminID, v))
}

// AssignedAdminIDIn applies the In predicate on the "assigned_admin_id" field.
func AssignedAdminIDIn(vs ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldAssignedAdminID, vs...))
}

// AssignedAdminIDNotIn applies the NotIn predicate on the "assigned_admin_id" field.
func AssignedAdminIDNotIn(vs ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldAssignedAdminID, vs...))
}

// AssignedAdminIDIsNil applies the IsNil predicate on the "assigned_admin_id" field.
func AssignedAdminIDIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldAssignedAdminID))
}

// AssignedAdminIDNotNil applies the NotNil predicate on the "assigned_admin_id" field.
func AssignedAdminIDNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldAssignedAdminID))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldClosedAt))
}

// ClosedByEQ applies the EQ predicate on the "closed_by" field.
func ClosedByEQ(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldClosedBy, v))
}

// ClosedByNEQ applies the NEQ predicate on the "closed_by" field.
func ClosedByNEQ(v int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldClosedBy, v))
}

// ClosedByIn applies the In predicate on the "closed_by" field.
func ClosedByIn(vs ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldClosedBy, vs...))
}

// ClosedByNotIn applies the NotIn predicate on the "closed_by" field.
func ClosedByNotIn(vs ...int64) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldClosedBy, vs...))
}

// ClosedByIsNil applies the IsNil predicate on the "closed_by" field.
func ClosedByIsNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIsNull(FieldClosedBy))
}

// ClosedByNotNil applies the NotNil predicate on the "closed_by" field.
func ClosedByNotNil() predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotNull(FieldClosedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupportTicket {
	return predicate.SupportTicket(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedAdmin applies the HasEdge predicate on the "assigned_admin" edge.
func HasAssignedAdmin() predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedAdminTable, AssignedAdminColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedAdminWith applies the HasEdge predicate on the "assigned_admin" edge with a given conditions (other predicates).
func HasAssignedAdminWith(preds ...predicate.User) predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := newAssignedAdminStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClosedByUser applies the HasEdge predicate on the "closed_by_user" edge.
func HasClosedByUser() predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClosedByUserTable, ClosedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClosedByUserWith applies the HasEdge predicate on the "closed_by_user" edge with a given conditions (other predicates).
func HasClosedByUserWith(preds ...predicate.User) predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := newClosedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.SupportTicketMessage) predicate.SupportTicket {
	return predicate.SupportTicket(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportTicket) predicate.SupportTicket {
	return predicate.SupportTicket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportTicket) predicate.SupportTicket {
	return predicate.SupportTicket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportTicket) predicate.SupportTicket {
	return predicate.SupportTicket(sql.NotPredicates(p))
}
