// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcampaign"
)

// RedeemCampaignUpdate is the builder for updating RedeemCampaign entities.
type RedeemCampaignUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemCampaignMutation
}

// Where appends a list predicates to the RedeemCampaignUpdate builder.
func (_u *RedeemCampaignUpdate) Where(ps ...predicate.RedeemCampaign) *RedeemCampaignUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RedeemCampaignUpdate) SetName(v string) *RedeemCampaignUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RedeemCampaignUpdate) SetNillableName(v *string) *RedeemCampaignUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RedeemCampaignUpdate) SetStatus(v string) *RedeemCampaignUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RedeemCampaignUpdate) SetNillableStatus(v *string) *RedeemCampaignUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RedeemCampaignUpdate) SetCreatedBy(v int64) *RedeemCampaignUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RedeemCampaignUpdate) SetNillableCreatedBy(v *int64) *RedeemCampaignUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RedeemCampaignUpdate) AddCreatedBy(v int64) *RedeemCampaignUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RedeemCampaignUpdate) SetExpiresAt(v time.Time) *RedeemCampaignUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RedeemCampaignUpdate) SetNillableExpiresAt(v *time.Time) *RedeemCampaignUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RedeemCampaignUpdate) ClearExpiresAt() *RedeemCampaignUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the RedeemCampaignMutation object of the builder.
func (_u *RedeemCampaignUpdate) Mutation() *RedeemCampaignMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemCampaignUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCampaignUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemCampaignUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCampaignUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCampaignUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := redeemcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RedeemCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := redeemcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RedeemCampaign.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemCampaignUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcampaign.Table, redeemcampaign.Columns, sqlgraph.NewFieldSpec(redeemcampaign.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(redeemcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(redeemcampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(redeemcampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(redeemcampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(redeemcampaign.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(redeemcampaign.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemCampaignUpdateOne is the builder for updating a single RedeemCampaign entity.
type RedeemCampaignUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemCampaignMutation
}

// SetName sets the "name" field.
func (_u *RedeemCampaignUpdateOne) SetName(v string) *RedeemCampaignUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RedeemCampaignUpdateOne) SetNillableName(v *string) *RedeemCampaignUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RedeemCampaignUpdateOne) SetStatus(v string) *RedeemCampaignUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RedeemCampaignUpdateOne) SetNillableStatus(v *string) *RedeemCampaignUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *RedeemCampaignUpdateOne) SetCreatedBy(v int64) *RedeemCampaignUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *RedeemCampaignUpdateOne) SetNillableCreatedBy(v *int64) *RedeemCampaignUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *RedeemCampaignUpdateOne) AddCreatedBy(v int64) *RedeemCampaignUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RedeemCampaignUpdateOne) SetExpiresAt(v time.Time) *RedeemCampaignUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RedeemCampaignUpdateOne) SetNillableExpiresAt(v *time.Time) *RedeemCampaignUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *RedeemCampaignUpdateOne) ClearExpiresAt() *RedeemCampaignUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the RedeemCampaignMutation object of the builder.
func (_u *RedeemCampaignUpdateOne) Mutation() *RedeemCampaignMutation {
	return _u.mutation
}

// Where appends a list predicates to the RedeemCampaignUpdate builder.
func (_u *RedeemCampaignUpdateOne) Where(ps ...predicate.RedeemCampaign) *RedeemCampaignUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemCampaignUpdateOne) Select(field string, fields ...string) *RedeemCampaignUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemCampaign entity.
func (_u *RedeemCampaignUpdateOne) Save(ctx context.Context) (*RedeemCampaign, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCampaignUpdateOne) SaveX(ctx context.Context) *RedeemCampaign {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemCampaignUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCampaignUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RedeemCampaignUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := redeemcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RedeemCampaign.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := redeemcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RedeemCampaign.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RedeemCampaignUpdateOne) sqlSave(ctx context.Context) (_node *RedeemCampaign, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redeemcampaign.Table, redeemcampaign.Columns, sqlgraph.NewFieldSpec(redeemcampaign.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemCampaign.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcampaign.FieldID)
		for _, f := range fields {
			if !redeemcampaign.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemcampaign.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(redeemcampaign.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(redeemcampaign.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(redeemcampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(redeemcampaign.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(redeemcampaign.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(redeemcampaign.FieldExpiresAt, field.TypeTime)
	}
	_node = &RedeemCampaign{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcampaign.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
