// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/redeemcampaignredemption"
)

// RedeemCampaignRedemption is the model entity for the RedeemCampaignRedemption schema.
type RedeemCampaignRedemption struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID int64 `json:"campaign_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RedeemCodeID holds the value of the "redeem_code_id" field.
	RedeemCodeID *int64 `json:"redeem_code_id,omitempty"`
	// RedeemedAt holds the value of the "redeemed_at" field.
	RedeemedAt   time.Time `json:"redeemed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedeemCampaignRedemption) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redeemcampaignredemption.FieldID, redeemcampaignredemption.FieldCampaignID, redeemcampaignredemption.FieldUserID, redeemcampaignredemption.FieldRedeemCodeID:
			values[i] = new(sql.NullInt64)
		case redeemcampaignredemption.FieldRedeemedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedeemCampaignRedemption fields.
func (_m *RedeemCampaignRedemption) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redeemcampaignredemption.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case redeemcampaignredemption.FieldCampaignID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.Int64
			}
		case redeemcampaignredemption.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case redeemcampaignredemption.FieldRedeemCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redeem_code_id", values[i])
			} else if value.Valid {
				_m.RedeemCodeID = new(int64)
				*_m.RedeemCodeID = value.Int64
			}
		case redeemcampaignredemption.FieldRedeemedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field redeemed_at", values[i])
			} else if value.Valid {
				_m.RedeemedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedeemCampaignRedemption.
// This includes values selected through modifiers, order, etc.
func (_m *RedeemCampaignRedemption) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RedeemCampaignRedemption.
// Note that you need to call RedeemCampaignRedemption.Unwrap() before calling this method if this RedeemCampaignRedemption
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedeemCampaignRedemption) Update() *RedeemCampaignRedemptionUpdateOne {
	return NewRedeemCampaignRedemptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedeemCampaignRedemption entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedeemCampaignRedemption) Unwrap() *RedeemCampaignRedemption {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedeemCampaignRedemption is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedeemCampaignRedemption) String() string {
	var builder strings.Builder
	builder.WriteString("RedeemCampaignRedemption(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("campaign_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CampaignID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.RedeemCodeID; v != nil {
		builder.WriteString("redeem_code_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("redeemed_at=")
	builder.WriteString(_m.RedeemedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RedeemCampaignRedemptions is a parsable slice of RedeemCampaignRedemption.
type RedeemCampaignRedemptions []*RedeemCampaignRedemption
