// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcampaign"
)

// RedeemCampaignCreate is the builder for creating a RedeemCampaign entity.
type RedeemCampaignCreate struct {
	config
	mutation *RedeemCampaignMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *RedeemCampaignCreate) SetName(v string) *RedeemCampaignCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RedeemCampaignCreate) SetStatus(v string) *RedeemCampaignCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RedeemCampaignCreate) SetNillableStatus(v *string) *RedeemCampaignCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *RedeemCampaignCreate) SetCreatedBy(v int64) *RedeemCampaignCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RedeemCampaignCreate) SetExpiresAt(v time.Time) *RedeemCampaignCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *RedeemCampaignCreate) SetNillableExpiresAt(v *time.Time) *RedeemCampaignCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RedeemCampaignCreate) SetCreatedAt(v time.Time) *RedeemCampaignCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RedeemCampaignCreate) SetNillableCreatedAt(v *time.Time) *RedeemCampaignCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the RedeemCampaignMutation object of the builder.
func (_c *RedeemCampaignCreate) Mutation() *RedeemCampaignMutation {
	return _c.mutation
}

// Save creates the RedeemCampaign in the database.
func (_c *RedeemCampaignCreate) Save(ctx context.Context) (*RedeemCampaign, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCampaignCreate) SaveX(ctx context.Context) *RedeemCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCampaignCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCampaignCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCampaignCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := redeemcampaign.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := redeemcampaign.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCampaignCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RedeemCampaign.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := redeemcampaign.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RedeemCampaign.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RedeemCampaign.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := redeemcampaign.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RedeemCampaign.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "RedeemCampaign.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RedeemCampaign.created_at"`)}
	}
	return nil
}

func (_c *RedeemCampaignCreate) sqlSave(ctx context.Context) (*RedeemCampaign, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCampaignCreate) createSpec() (*RedeemCampaign, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCampaign{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcampaign.Table, sqlgraph.NewFieldSpec(redeemcampaign.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(redeemcampaign.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(redeemcampaign.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(redeemcampaign.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(redeemcampaign.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(redeemcampaign.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCampaign.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCampaignUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCampaignCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCampaignUpsertOne {
	_c.conflict = opts
	return &RedeemCampaignUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCampaignCreate) OnConflictColumns(columns ...string) *RedeemCampaignUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCampaignUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCampaignUpsertOne is the builder for "upsert"-ing
	//  one RedeemCampaign node.
	RedeemCampaignUpsertOne struct {
		create *RedeemCampaignCreate
	}

	// RedeemCampaignUpsert is the "OnConflict" setter.
	RedeemCampaignUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *RedeemCampaignUpsert) SetName(v string) *RedeemCampaignUpsert {
	u.Set(redeemcampaign.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RedeemCampaignUpsert) UpdateName() *RedeemCampaignUpsert {
	u.SetExcluded(redeemcampaign.FieldName)
	return u
}

// SetStatus sets the "status" field.
func (u *RedeemCampaignUpsert) SetStatus(v string) *RedeemCampaignUpsert {
	u.Set(redeemcampaign.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RedeemCampaignUpsert) UpdateStatus() *RedeemCampaignUpsert {
	u.SetExcluded(redeemcampaign.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *RedeemCampaignUpsert) SetCreatedBy(v int64) *RedeemCampaignUpsert {
	u.Set(redeemcampaign.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RedeemCampaignUpsert) UpdateCreatedBy() *RedeemCampaignUpsert {
	u.SetExcluded(redeemcampaign.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RedeemCampaignUpsert) AddCreatedBy(v int64) *RedeemCampaignUpsert {
	u.Add(redeemcampaign.FieldCreatedBy, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *RedeemCampaignUpsert) SetExpiresAt(v time.Time) *RedeemCampaignUpsert {
	u.Set(redeemcampaign.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RedeemCampaignUpsert) UpdateExpiresAt() *RedeemCampaignUpsert {
	u.SetExcluded(redeemcampaign.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RedeemCampaignUpsert) ClearExpiresAt() *RedeemCampaignUpsert {
	u.SetNull(redeemcampaign.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCampaignUpsertOne) UpdateNewValues() *RedeemCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(redeemcampaign.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCampaign.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCampaignUpsertOne) Ignore() *RedeemCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCampaignUpsertOne) DoNothing() *RedeemCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCampaignCreate.OnConflict
// documentation for more info.
func (u *RedeemCampaignUpsertOne) Update(set func(*RedeemCampaignUpsert)) *RedeemCampaignUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RedeemCampaignUpsertOne) SetName(v string) *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RedeemCampaignUpsertOne) UpdateName() *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *RedeemCampaignUpsertOne) SetStatus(v string) *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RedeemCampaignUpsertOne) UpdateStatus() *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RedeemCampaignUpsertOne) SetCreatedBy(v int64) *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RedeemCampaignUpsertOne) AddCreatedBy(v int64) *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RedeemCampaignUpsertOne) UpdateCreatedBy() *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RedeemCampaignUpsertOne) SetExpiresAt(v time.Time) *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RedeemCampaignUpsertOne) UpdateExpiresAt() *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RedeemCampaignUpsertOne) ClearExpiresAt() *RedeemCampaignUpsertOne {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *RedeemCampaignUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCampaignCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCampaignUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCampaignUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCampaignUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCampaignCreateBulk is the builder for creating many RedeemCampaign entities in bulk.
type RedeemCampaignCreateBulk struct {
	config
	err      error
	builders []*RedeemCampaignCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCampaign entities in the database.
func (_c *RedeemCampaignCreateBulk) Save(ctx context.Context) ([]*RedeemCampaign, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCampaign, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCampaignMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCampaignCreateBulk) SaveX(ctx context.Context) []*RedeemCampaign {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCampaignCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCampaignCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCampaign.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCampaignUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCampaignCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCampaignUpsertBulk {
	_c.conflict = opts
	return &RedeemCampaignUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCampaign.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCampaignCreateBulk) OnConflictColumns(columns ...string) *RedeemCampaignUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCampaignUpsertBulk{
		create: _c,
	}
}

// RedeemCampaignUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCampaign nodes.
type RedeemCampaignUpsertBulk struct {
	create *RedeemCampaignCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCampaign.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCampaignUpsertBulk) UpdateNewValues() *RedeemCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(redeemcampaign.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCampaign.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCampaignUpsertBulk) Ignore() *RedeemCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCampaignUpsertBulk) DoNothing() *RedeemCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCampaignCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCampaignUpsertBulk) Update(set func(*RedeemCampaignUpsert)) *RedeemCampaignUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCampaignUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RedeemCampaignUpsertBulk) SetName(v string) *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RedeemCampaignUpsertBulk) UpdateName() *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateName()
	})
}

// SetStatus sets the "status" field.
func (u *RedeemCampaignUpsertBulk) SetStatus(v string) *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RedeemCampaignUpsertBulk) UpdateStatus() *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *RedeemCampaignUpsertBulk) SetCreatedBy(v int64) *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *RedeemCampaignUpsertBulk) AddCreatedBy(v int64) *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *RedeemCampaignUpsertBulk) UpdateCreatedBy() *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *RedeemCampaignUpsertBulk) SetExpiresAt(v time.Time) *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *RedeemCampaignUpsertBulk) UpdateExpiresAt() *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *RedeemCampaignUpsertBulk) ClearExpiresAt() *RedeemCampaignUpsertBulk {
	return u.Update(func(s *RedeemCampaignUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *RedeemCampaignUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCampaignCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCampaignCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCampaignUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
