// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcampaign"
)

// RedeemCampaignDelete is the builder for deleting a RedeemCampaign entity.
type RedeemCampaignDelete struct {
	config
	hooks    []Hook
	mutation *RedeemCampaignMutation
}

// Where appends a list predicates to the RedeemCampaignDelete builder.
func (_d *RedeemCampaignDelete) Where(ps ...predicate.RedeemCampaign) *RedeemCampaignDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RedeemCampaignDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RedeemCampaignDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RedeemCampaignDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(redeemcampaign.Table, sqlgraph.NewFieldSpec(redeemcampaign.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RedeemCampaignDeleteOne is the builder for deleting a single RedeemCampaign entity.
type RedeemCampaignDeleteOne struct {
	_d *RedeemCampaignDelete
}

// Where appends a list predicates to the RedeemCampaignDelete builder.
func (_d *RedeemCampaignDeleteOne) Where(ps ...predicate.RedeemCampaign) *RedeemCampaignDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RedeemCampaignDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{redeemcampaign.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RedeemCampaignDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
