// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/redeemcampaignredemption"
)

// RedeemCampaignRedemptionUpdate is the builder for updating RedeemCampaignRedemption entities.
type RedeemCampaignRedemptionUpdate struct {
	config
	hooks    []Hook
	mutation *RedeemCampaignRedemptionMutation
}

// Where appends a list predicates to the RedeemCampaignRedemptionUpdate builder.
func (_u *RedeemCampaignRedemptionUpdate) Where(ps ...predicate.RedeemCampaignRedemption) *RedeemCampaignRedemptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *RedeemCampaignRedemptionUpdate) SetCampaignID(v int64) *RedeemCampaignRedemptionUpdate {
	_u.mutation.ResetCampaignID()
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdate) SetNillableCampaignID(v *int64) *RedeemCampaignRedemptionUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// AddCampaignID adds value to the "campaign_id" field.
func (_u *RedeemCampaignRedemptionUpdate) AddCampaignID(v int64) *RedeemCampaignRedemptionUpdate {
	_u.mutation.AddCampaignID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCampaignRedemptionUpdate) SetUserID(v int64) *RedeemCampaignRedemptionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdate) SetNillableUserID(v *int64) *RedeemCampaignRedemptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RedeemCampaignRedemptionUpdate) AddUserID(v int64) *RedeemCampaignRedemptionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCampaignRedemptionUpdate) SetRedeemCodeID(v int64) *RedeemCampaignRedemptionUpdate {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdate) SetNillableRedeemCodeID(v *int64) *RedeemCampaignRedemptionUpdate {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *RedeemCampaignRedemptionUpdate) AddRedeemCodeID(v int64) *RedeemCampaignRedemptionUpdate {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *RedeemCampaignRedemptionUpdate) ClearRedeemCodeID() *RedeemCampaignRedemptionUpdate {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_u *RedeemCampaignRedemptionUpdate) SetRedeemedAt(v time.Time) *RedeemCampaignRedemptionUpdate {
	_u.mutation.SetRedeemedAt(v)
	return _u
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdate) SetNillableRedeemedAt(v *time.Time) *RedeemCampaignRedemptionUpdate {
	if v != nil {
		_u.SetRedeemedAt(*v)
	}
	return _u
}

// Mutation returns the RedeemCampaignRedemptionMutation object of the builder.
func (_u *RedeemCampaignRedemptionUpdate) Mutation() *RedeemCampaignRedemptionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RedeemCampaignRedemptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCampaignRedemptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RedeemCampaignRedemptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCampaignRedemptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RedeemCampaignRedemptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(redeemcampaignredemption.Table, redeemcampaignredemption.Columns, sqlgraph.NewFieldSpec(redeemcampaignredemption.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CampaignID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCampaignID(); ok {
		_spec.AddField(redeemcampaignredemption.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(redeemcampaignredemption.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodeIDCleared() {
		_spec.ClearField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RedeemedAt(); ok {
		_spec.SetField(redeemcampaignredemption.FieldRedeemedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcampaignredemption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RedeemCampaignRedemptionUpdateOne is the builder for updating a single RedeemCampaignRedemption entity.
type RedeemCampaignRedemptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedeemCampaignRedemptionMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) SetCampaignID(v int64) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.ResetCampaignID()
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdateOne) SetNillableCampaignID(v *int64) *RedeemCampaignRedemptionUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// AddCampaignID adds value to the "campaign_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) AddCampaignID(v int64) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.AddCampaignID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) SetUserID(v int64) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdateOne) SetNillableUserID(v *int64) *RedeemCampaignRedemptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) AddUserID(v int64) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) SetRedeemCodeID(v int64) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.ResetRedeemCodeID()
	_u.mutation.SetRedeemCodeID(v)
	return _u
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdateOne) SetNillableRedeemCodeID(v *int64) *RedeemCampaignRedemptionUpdateOne {
	if v != nil {
		_u.SetRedeemCodeID(*v)
	}
	return _u
}

// AddRedeemCodeID adds value to the "redeem_code_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) AddRedeemCodeID(v int64) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.AddRedeemCodeID(v)
	return _u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (_u *RedeemCampaignRedemptionUpdateOne) ClearRedeemCodeID() *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.ClearRedeemCodeID()
	return _u
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_u *RedeemCampaignRedemptionUpdateOne) SetRedeemedAt(v time.Time) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.SetRedeemedAt(v)
	return _u
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_u *RedeemCampaignRedemptionUpdateOne) SetNillableRedeemedAt(v *time.Time) *RedeemCampaignRedemptionUpdateOne {
	if v != nil {
		_u.SetRedeemedAt(*v)
	}
	return _u
}

// Mutation returns the RedeemCampaignRedemptionMutation object of the builder.
func (_u *RedeemCampaignRedemptionUpdateOne) Mutation() *RedeemCampaignRedemptionMutation {
	return _u.mutation
}

// Where appends a list predicates to the RedeemCampaignRedemptionUpdate builder.
func (_u *RedeemCampaignRedemptionUpdateOne) Where(ps ...predicate.RedeemCampaignRedemption) *RedeemCampaignRedemptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RedeemCampaignRedemptionUpdateOne) Select(field string, fields ...string) *RedeemCampaignRedemptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RedeemCampaignRedemption entity.
func (_u *RedeemCampaignRedemptionUpdateOne) Save(ctx context.Context) (*RedeemCampaignRedemption, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RedeemCampaignRedemptionUpdateOne) SaveX(ctx context.Context) *RedeemCampaignRedemption {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RedeemCampaignRedemptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RedeemCampaignRedemptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RedeemCampaignRedemptionUpdateOne) sqlSave(ctx context.Context) (_node *RedeemCampaignRedemption, err error) {
	_spec := sqlgraph.NewUpdateSpec(redeemcampaignredemption.Table, redeemcampaignredemption.Columns, sqlgraph.NewFieldSpec(redeemcampaignredemption.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedeemCampaignRedemption.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redeemcampaignredemption.FieldID)
		for _, f := range fields {
			if !redeemcampaignredemption.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redeemcampaignredemption.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CampaignID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCampaignID(); ok {
		_spec.AddField(redeemcampaignredemption.FieldCampaignID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(redeemcampaignredemption.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRedeemCodeID(); ok {
		_spec.AddField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64, value)
	}
	if _u.mutation.RedeemCodeIDCleared() {
		_spec.ClearField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64)
	}
	if value, ok := _u.mutation.RedeemedAt(); ok {
		_spec.SetField(redeemcampaignredemption.FieldRedeemedAt, field.TypeTime, value)
	}
	_node = &RedeemCampaignRedemption{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redeemcampaignredemption.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
