// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcampaignredemption"
)

// RedeemCampaignRedemptionCreate is the builder for creating a RedeemCampaignRedemption entity.
type RedeemCampaignRedemptionCreate struct {
	config
	mutation *RedeemCampaignRedemptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCampaignID sets the "campaign_id" field.
func (_c *RedeemCampaignRedemptionCreate) SetCampaignID(v int64) *RedeemCampaignRedemptionCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RedeemCampaignRedemptionCreate) SetUserID(v int64) *RedeemCampaignRedemptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemCampaignRedemptionCreate) SetRedeemCodeID(v int64) *RedeemCampaignRedemptionCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetNillableRedeemCodeID sets the "redeem_code_id" field if the given value is not nil.
func (_c *RedeemCampaignRedemptionCreate) SetNillableRedeemCodeID(v *int64) *RedeemCampaignRedemptionCreate {
	if v != nil {
		_c.SetRedeemCodeID(*v)
	}
	return _c
}

// SetRedeemedAt sets the "redeemed_at" field.
func (_c *RedeemCampaignRedemptionCreate) SetRedeemedAt(v time.Time) *RedeemCampaignRedemptionCreate {
	_c.mutation.SetRedeemedAt(v)
	return _c
}

// SetNillableRedeemedAt sets the "redeemed_at" field if the given value is not nil.
func (_c *RedeemCampaignRedemptionCreate) SetNillableRedeemedAt(v *time.Time) *RedeemCampaignRedemptionCreate {
	if v != nil {
		_c.SetRedeemedAt(*v)
	}
	return _c
}

// Mutation returns the RedeemCampaignRedemptionMutation object of the builder.
func (_c *RedeemCampaignRedemptionCreate) Mutation() *RedeemCampaignRedemptionMutation {
	return _c.mutation
}

// Save creates the RedeemCampaignRedemption in the database.
func (_c *RedeemCampaignRedemptionCreate) Save(ctx context.Context) (*RedeemCampaignRedemption, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCampaignRedemptionCreate) SaveX(ctx context.Context) *RedeemCampaignRedemption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCampaignRedemptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCampaignRedemptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCampaignRedemptionCreate) defaults() {
	if _, ok := _c.mutation.RedeemedAt(); !ok {
		v := redeemcampaignredemption.DefaultRedeemedAt()
		_c.mutation.SetRedeemedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCampaignRedemptionCreate) check() error {
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "RedeemCampaignRedemption.campaign_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RedeemCampaignRedemption.user_id"`)}
	}
	if _, ok := _c.mutation.RedeemedAt(); !ok {
		return &ValidationError{Name: "redeemed_at", err: errors.New(`ent: missing required field "RedeemCampaignRedemption.redeemed_at"`)}
	}
	return nil
}

func (_c *RedeemCampaignRedemptionCreate) sqlSave(ctx context.Context) (*RedeemCampaignRedemption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCampaignRedemptionCreate) createSpec() (*RedeemCampaignRedemption, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCampaignRedemption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcampaignredemption.Table, sqlgraph.NewFieldSpec(redeemcampaignredemption.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CampaignID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldCampaignID, field.TypeInt64, value)
		_node.CampaignID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RedeemCodeID(); ok {
		_spec.SetField(redeemcampaignredemption.FieldRedeemCodeID, field.TypeInt64, value)
		_node.RedeemCodeID = &value
	}
	if value, ok := _c.mutation.RedeemedAt(); ok {
		_spec.SetField(redeemcampaignredemption.FieldRedeemedAt, field.TypeTime, value)
		_node.RedeemedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCampaignRedemption.Create().
//		SetCampaignID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCampaignRedemptionUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCampaignRedemptionCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCampaignRedemptionUpsertOne {
	_c.conflict = opts
	return &RedeemCampaignRedemptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCampaignRedemption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCampaignRedemptionCreate) OnConflictColumns(columns ...string) *RedeemCampaignRedemptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCampaignRedemptionUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCampaignRedemptionUpsertOne is the builder for "upsert"-ing
	//  one RedeemCampaignRedemption node.
	RedeemCampaignRedemptionUpsertOne struct {
		create *RedeemCampaignRedemptionCreate
	}

	// RedeemCampaignRedemptionUpsert is the "OnConflict" setter.
	RedeemCampaignRedemptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetCampaignID sets the "campaign_id" field.
func (u *RedeemCampaignRedemptionUpsert) SetCampaignID(v int64) *RedeemCampaignRedemptionUpsert {
	u.Set(redeemcampaignredemption.FieldCampaignID, v)
	return u
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsert) UpdateCampaignID() *RedeemCampaignRedemptionUpsert {
	u.SetExcluded(redeemcampaignredemption.FieldCampaignID)
	return u
}

// AddCampaignID adds v to the "campaign_id" field.
func (u *RedeemCampaignRedemptionUpsert) AddCampaignID(v int64) *RedeemCampaignRedemptionUpsert {
	u.Add(redeemcampaignredemption.FieldCampaignID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RedeemCampaignRedemptionUpsert) SetUserID(v int64) *RedeemCampaignRedemptionUpsert {
	u.Set(redeemcampaignredemption.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsert) UpdateUserID() *RedeemCampaignRedemptionUpsert {
	u.SetExcluded(redeemcampaignredemption.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *RedeemCampaignRedemptionUpsert) AddUserID(v int64) *RedeemCampaignRedemptionUpsert {
	u.Add(redeemcampaignredemption.FieldUserID, v)
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsert) SetRedeemCodeID(v int64) *RedeemCampaignRedemptionUpsert {
	u.Set(redeemcampaignredemption.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsert) UpdateRedeemCodeID() *RedeemCampaignRedemptionUpsert {
	u.SetExcluded(redeemcampaignredemption.FieldRedeemCodeID)
	return u
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsert) AddRedeemCodeID(v int64) *RedeemCampaignRedemptionUpsert {
	u.Add(redeemcampaignredemption.FieldRedeemCodeID, v)
	return u
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsert) ClearRedeemCodeID() *RedeemCampaignRedemptionUpsert {
	u.SetNull(redeemcampaignredemption.FieldRedeemCodeID)
	return u
}

// SetRedeemedAt sets the "redeemed_at" field.
func (u *RedeemCampaignRedemptionUpsert) SetRedeemedAt(v time.Time) *RedeemCampaignRedemptionUpsert {
	u.Set(redeemcampaignredemption.FieldRedeemedAt, v)
	return u
}

// UpdateRedeemedAt sets the "redeemed_at" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsert) UpdateRedeemedAt() *RedeemCampaignRedemptionUpsert {
	u.SetExcluded(redeemcampaignredemption.FieldRedeemedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCampaignRedemption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCampaignRedemptionUpsertOne) UpdateNewValues() *RedeemCampaignRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCampaignRedemption.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCampaignRedemptionUpsertOne) Ignore() *RedeemCampaignRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCampaignRedemptionUpsertOne) DoNothing() *RedeemCampaignRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCampaignRedemptionCreate.OnConflict
// documentation for more info.
func (u *RedeemCampaignRedemptionUpsertOne) Update(set func(*RedeemCampaignRedemptionUpsert)) *RedeemCampaignRedemptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCampaignRedemptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) SetCampaignID(v int64) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetCampaignID(v)
	})
}

// AddCampaignID adds v to the "campaign_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) AddCampaignID(v int64) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.AddCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertOne) UpdateCampaignID() *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateCampaignID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) SetUserID(v int64) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) AddUserID(v int64) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertOne) UpdateUserID() *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) SetRedeemCodeID(v int64) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) AddRedeemCodeID(v int64) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertOne) UpdateRedeemCodeID() *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsertOne) ClearRedeemCodeID() *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetRedeemedAt sets the "redeemed_at" field.
func (u *RedeemCampaignRedemptionUpsertOne) SetRedeemedAt(v time.Time) *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetRedeemedAt(v)
	})
}

// UpdateRedeemedAt sets the "redeemed_at" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertOne) UpdateRedeemedAt() *RedeemCampaignRedemptionUpsertOne {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateRedeemedAt()
	})
}

// Exec executes the query.
func (u *RedeemCampaignRedemptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCampaignRedemptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCampaignRedemptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCampaignRedemptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCampaignRedemptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCampaignRedemptionCreateBulk is the builder for creating many RedeemCampaignRedemption entities in bulk.
type RedeemCampaignRedemptionCreateBulk struct {
	config
	err      error
	builders []*RedeemCampaignRedemptionCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCampaignRedemption entities in the database.
func (_c *RedeemCampaignRedemptionCreateBulk) Save(ctx context.Context) ([]*RedeemCampaignRedemption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCampaignRedemption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCampaignRedemptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCampaignRedemptionCreateBulk) SaveX(ctx context.Context) []*RedeemCampaignRedemption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCampaignRedemptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCampaignRedemptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCampaignRedemption.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCampaignRedemptionUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCampaignRedemptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCampaignRedemptionUpsertBulk {
	_c.conflict = opts
	return &RedeemCampaignRedemptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCampaignRedemption.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCampaignRedemptionCreateBulk) OnConflictColumns(columns ...string) *RedeemCampaignRedemptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCampaignRedemptionUpsertBulk{
		create: _c,
	}
}

// RedeemCampaignRedemptionUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCampaignRedemption nodes.
type RedeemCampaignRedemptionUpsertBulk struct {
	create *RedeemCampaignRedemptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCampaignRedemption.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCampaignRedemptionUpsertBulk) UpdateNewValues() *RedeemCampaignRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCampaignRedemption.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCampaignRedemptionUpsertBulk) Ignore() *RedeemCampaignRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCampaignRedemptionUpsertBulk) DoNothing() *RedeemCampaignRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCampaignRedemptionCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCampaignRedemptionUpsertBulk) Update(set func(*RedeemCampaignRedemptionUpsert)) *RedeemCampaignRedemptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCampaignRedemptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) SetCampaignID(v int64) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetCampaignID(v)
	})
}

// AddCampaignID adds v to the "campaign_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) AddCampaignID(v int64) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.AddCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertBulk) UpdateCampaignID() *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateCampaignID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) SetUserID(v int64) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) AddUserID(v int64) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertBulk) UpdateUserID() *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateUserID()
	})
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) SetRedeemCodeID(v int64) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// AddRedeemCodeID adds v to the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) AddRedeemCodeID(v int64) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.AddRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertBulk) UpdateRedeemCodeID() *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// ClearRedeemCodeID clears the value of the "redeem_code_id" field.
func (u *RedeemCampaignRedemptionUpsertBulk) ClearRedeemCodeID() *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.ClearRedeemCodeID()
	})
}

// SetRedeemedAt sets the "redeemed_at" field.
func (u *RedeemCampaignRedemptionUpsertBulk) SetRedeemedAt(v time.Time) *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.SetRedeemedAt(v)
	})
}

// UpdateRedeemedAt sets the "redeemed_at" field to the value that was provided on create.
func (u *RedeemCampaignRedemptionUpsertBulk) UpdateRedeemedAt() *RedeemCampaignRedemptionUpsertBulk {
	return u.Update(func(s *RedeemCampaignRedemptionUpsert) {
		s.UpdateRedeemedAt()
	})
}

// Exec executes the query.
func (u *RedeemCampaignRedemptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCampaignRedemptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCampaignRedemptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCampaignRedemptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
