// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupportTicketUpdate is the builder for updating SupportTicket entities.
type SupportTicketUpdate struct {
	config
	hooks    []Hook
	mutation *SupportTicketMutation
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdate) Where(ps ...predicate.SupportTicket) *SupportTicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdate) SetUserID(v int64) *SupportTicketUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketUpdate) SetTitle(v string) *SupportTicketUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableTitle(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdate) SetCategory(v string) *SupportTicketUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableCategory(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdate) SetStatus(v string) *SupportTicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableStatus(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportTicketUpdate) SetPriority(v string) *SupportTicketUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillablePriority(v *string) *SupportTicketUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportTicketUpdate) SetLastMessageAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastMessageAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *SupportTicketUpdate) ClearLastMessageAt() *SupportTicketUpdate {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetLastUserMessageAt sets the "last_user_message_at" field.
func (_u *SupportTicketUpdate) SetLastUserMessageAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastUserMessageAt(v)
	return _u
}

// SetNillableLastUserMessageAt sets the "last_user_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastUserMessageAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastUserMessageAt(*v)
	}
	return _u
}

// ClearLastUserMessageAt clears the value of the "last_user_message_at" field.
func (_u *SupportTicketUpdate) ClearLastUserMessageAt() *SupportTicketUpdate {
	_u.mutation.ClearLastUserMessageAt()
	return _u
}

// SetLastAdminMessageAt sets the "last_admin_message_at" field.
func (_u *SupportTicketUpdate) SetLastAdminMessageAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetLastAdminMessageAt(v)
	return _u
}

// SetNillableLastAdminMessageAt sets the "last_admin_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableLastAdminMessageAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetLastAdminMessageAt(*v)
	}
	return _u
}

// ClearLastAdminMessageAt clears the value of the "last_admin_message_at" field.
func (_u *SupportTicketUpdate) ClearLastAdminMessageAt() *SupportTicketUpdate {
	_u.mutation.ClearLastAdminMessageAt()
	return _u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_u *SupportTicketUpdate) SetUserLastReadAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUserLastReadAt(v)
	return _u
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableUserLastReadAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetUserLastReadAt(*v)
	}
	return _u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (_u *SupportTicketUpdate) ClearUserLastReadAt() *SupportTicketUpdate {
	_u.mutation.ClearUserLastReadAt()
	return _u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_u *SupportTicketUpdate) SetAdminLastReadAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetAdminLastReadAt(v)
	return _u
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableAdminLastReadAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetAdminLastReadAt(*v)
	}
	return _u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (_u *SupportTicketUpdate) ClearAdminLastReadAt() *SupportTicketUpdate {
	_u.mutation.ClearAdminLastReadAt()
	return _u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_u *SupportTicketUpdate) SetAssignedAdminID(v int64) *SupportTicketUpdate {
	_u.mutation.SetAssignedAdminID(v)
	return _u
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableAssignedAdminID(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetAssignedAdminID(*v)
	}
	return _u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (_u *SupportTicketUpdate) ClearAssignedAdminID() *SupportTicketUpdate {
	_u.mutation.ClearAssignedAdminID()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdate) SetClosedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedAt(v *time.Time) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdate) ClearClosedAt() *SupportTicketUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetClosedBy sets the "closed_by" field.
func (_u *SupportTicketUpdate) SetClosedBy(v int64) *SupportTicketUpdate {
	_u.mutation.SetClosedBy(v)
	return _u
}

// SetNillableClosedBy sets the "closed_by" field if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedBy(v *int64) *SupportTicketUpdate {
	if v != nil {
		_u.SetClosedBy(*v)
	}
	return _u
}

// ClearClosedBy clears the value of the "closed_by" field.
func (_u *SupportTicketUpdate) ClearClosedBy() *SupportTicketUpdate {
	_u.mutation.ClearClosedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdate) SetUpdatedAt(v time.Time) *SupportTicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupportTicketUpdate) SetUser(v *User) *SupportTicketUpdate {
	return _u.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_u *SupportTicketUpdate) SetAssignedAdmin(v *User) *SupportTicketUpdate {
	return _u.SetAssignedAdminID(v.ID)
}

// SetClosedByUserID sets the "closed_by_user" edge to the User entity by ID.
func (_u *SupportTicketUpdate) SetClosedByUserID(id int64) *SupportTicketUpdate {
	_u.mutation.SetClosedByUserID(id)
	return _u
}

// SetNillableClosedByUserID sets the "closed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SupportTicketUpdate) SetNillableClosedByUserID(id *int64) *SupportTicketUpdate {
	if id != nil {
		_u = _u.SetClosedByUserID(*id)
	}
	return _u
}

// SetClosedByUser sets the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdate) SetClosedByUser(v *User) *SupportTicketUpdate {
	return _u.SetClosedByUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportTicketMessage entity by IDs.
func (_u *SupportTicketUpdate) AddMessageIDs(ids ...int64) *SupportTicketUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdate) AddMessages(v ...*SupportTicketMessage) *SupportTicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdate) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupportTicketUpdate) ClearUser() *SupportTicketUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignedAdmin clears the "assigned_admin" edge to the User entity.
func (_u *SupportTicketUpdate) ClearAssignedAdmin() *SupportTicketUpdate {
	_u.mutation.ClearAssignedAdmin()
	return _u
}

// ClearClosedByUser clears the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdate) ClearClosedByUser() *SupportTicketUpdate {
	_u.mutation.ClearClosedByUser()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdate) ClearMessages() *SupportTicketUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportTicketMessage entities by IDs.
func (_u *SupportTicketUpdate) RemoveMessageIDs(ids ...int64) *SupportTicketUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportTicketMessage entities.
func (_u *SupportTicketUpdate) RemoveMessages(v ...*SupportTicketMessage) *SupportTicketUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportTicketUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportTicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicket.user"`)
	}
	return nil
}

func (_u *SupportTicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(supportticket.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUserMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastUserMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastUserMessageAtCleared() {
		_spec.ClearField(supportticket.FieldLastUserMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAdminMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastAdminMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastAdminMessageAtCleared() {
		_spec.ClearField(supportticket.FieldLastAdminMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserLastReadAt(); ok {
		_spec.SetField(supportticket.FieldUserLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.UserLastReadAtCleared() {
		_spec.ClearField(supportticket.FieldUserLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AdminLastReadAt(); ok {
		_spec.SetField(supportticket.FieldAdminLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.AdminLastReadAtCleared() {
		_spec.ClearField(supportticket.FieldAdminLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssignedAdminTable,
			Columns: []string{supportticket.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssignedAdminTable,
			Columns: []string{supportticket.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClosedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClosedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportTicketUpdateOne is the builder for updating a single SupportTicket entity.
type SupportTicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportTicketMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupportTicketUpdateOne) SetUserID(v int64) *SupportTicketUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *SupportTicketUpdateOne) SetTitle(v string) *SupportTicketUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableTitle(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *SupportTicketUpdateOne) SetCategory(v string) *SupportTicketUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableCategory(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportTicketUpdateOne) SetStatus(v string) *SupportTicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableStatus(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *SupportTicketUpdateOne) SetPriority(v string) *SupportTicketUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillablePriority(v *string) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *SupportTicketUpdateOne) SetLastMessageAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastMessageAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *SupportTicketUpdateOne) ClearLastMessageAt() *SupportTicketUpdateOne {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetLastUserMessageAt sets the "last_user_message_at" field.
func (_u *SupportTicketUpdateOne) SetLastUserMessageAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastUserMessageAt(v)
	return _u
}

// SetNillableLastUserMessageAt sets the "last_user_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastUserMessageAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastUserMessageAt(*v)
	}
	return _u
}

// ClearLastUserMessageAt clears the value of the "last_user_message_at" field.
func (_u *SupportTicketUpdateOne) ClearLastUserMessageAt() *SupportTicketUpdateOne {
	_u.mutation.ClearLastUserMessageAt()
	return _u
}

// SetLastAdminMessageAt sets the "last_admin_message_at" field.
func (_u *SupportTicketUpdateOne) SetLastAdminMessageAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetLastAdminMessageAt(v)
	return _u
}

// SetNillableLastAdminMessageAt sets the "last_admin_message_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableLastAdminMessageAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetLastAdminMessageAt(*v)
	}
	return _u
}

// ClearLastAdminMessageAt clears the value of the "last_admin_message_at" field.
func (_u *SupportTicketUpdateOne) ClearLastAdminMessageAt() *SupportTicketUpdateOne {
	_u.mutation.ClearLastAdminMessageAt()
	return _u
}

// SetUserLastReadAt sets the "user_last_read_at" field.
func (_u *SupportTicketUpdateOne) SetUserLastReadAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUserLastReadAt(v)
	return _u
}

// SetNillableUserLastReadAt sets the "user_last_read_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableUserLastReadAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetUserLastReadAt(*v)
	}
	return _u
}

// ClearUserLastReadAt clears the value of the "user_last_read_at" field.
func (_u *SupportTicketUpdateOne) ClearUserLastReadAt() *SupportTicketUpdateOne {
	_u.mutation.ClearUserLastReadAt()
	return _u
}

// SetAdminLastReadAt sets the "admin_last_read_at" field.
func (_u *SupportTicketUpdateOne) SetAdminLastReadAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetAdminLastReadAt(v)
	return _u
}

// SetNillableAdminLastReadAt sets the "admin_last_read_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableAdminLastReadAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetAdminLastReadAt(*v)
	}
	return _u
}

// ClearAdminLastReadAt clears the value of the "admin_last_read_at" field.
func (_u *SupportTicketUpdateOne) ClearAdminLastReadAt() *SupportTicketUpdateOne {
	_u.mutation.ClearAdminLastReadAt()
	return _u
}

// SetAssignedAdminID sets the "assigned_admin_id" field.
func (_u *SupportTicketUpdateOne) SetAssignedAdminID(v int64) *SupportTicketUpdateOne {
	_u.mutation.SetAssignedAdminID(v)
	return _u
}

// SetNillableAssignedAdminID sets the "assigned_admin_id" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableAssignedAdminID(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetAssignedAdminID(*v)
	}
	return _u
}

// ClearAssignedAdminID clears the value of the "assigned_admin_id" field.
func (_u *SupportTicketUpdateOne) ClearAssignedAdminID() *SupportTicketUpdateOne {
	_u.mutation.ClearAssignedAdminID()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *SupportTicketUpdateOne) SetClosedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedAt(v *time.Time) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *SupportTicketUpdateOne) ClearClosedAt() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// SetClosedBy sets the "closed_by" field.
func (_u *SupportTicketUpdateOne) SetClosedBy(v int64) *SupportTicketUpdateOne {
	_u.mutation.SetClosedBy(v)
	return _u
}

// SetNillableClosedBy sets the "closed_by" field if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedBy(v *int64) *SupportTicketUpdateOne {
	if v != nil {
		_u.SetClosedBy(*v)
	}
	return _u
}

// ClearClosedBy clears the value of the "closed_by" field.
func (_u *SupportTicketUpdateOne) ClearClosedBy() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportTicketUpdateOne) SetUpdatedAt(v time.Time) *SupportTicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupportTicketUpdateOne) SetUser(v *User) *SupportTicketUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAssignedAdmin sets the "assigned_admin" edge to the User entity.
func (_u *SupportTicketUpdateOne) SetAssignedAdmin(v *User) *SupportTicketUpdateOne {
	return _u.SetAssignedAdminID(v.ID)
}

// SetClosedByUserID sets the "closed_by_user" edge to the User entity by ID.
func (_u *SupportTicketUpdateOne) SetClosedByUserID(id int64) *SupportTicketUpdateOne {
	_u.mutation.SetClosedByUserID(id)
	return _u
}

// SetNillableClosedByUserID sets the "closed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *SupportTicketUpdateOne) SetNillableClosedByUserID(id *int64) *SupportTicketUpdateOne {
	if id != nil {
		_u = _u.SetClosedByUserID(*id)
	}
	return _u
}

// SetClosedByUser sets the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdateOne) SetClosedByUser(v *User) *SupportTicketUpdateOne {
	return _u.SetClosedByUserID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the SupportTicketMessage entity by IDs.
func (_u *SupportTicketUpdateOne) AddMessageIDs(ids ...int64) *SupportTicketUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdateOne) AddMessages(v ...*SupportTicketMessage) *SupportTicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the SupportTicketMutation object of the builder.
func (_u *SupportTicketUpdateOne) Mutation() *SupportTicketMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupportTicketUpdateOne) ClearUser() *SupportTicketUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAssignedAdmin clears the "assigned_admin" edge to the User entity.
func (_u *SupportTicketUpdateOne) ClearAssignedAdmin() *SupportTicketUpdateOne {
	_u.mutation.ClearAssignedAdmin()
	return _u
}

// ClearClosedByUser clears the "closed_by_user" edge to the User entity.
func (_u *SupportTicketUpdateOne) ClearClosedByUser() *SupportTicketUpdateOne {
	_u.mutation.ClearClosedByUser()
	return _u
}

// ClearMessages clears all "messages" edges to the SupportTicketMessage entity.
func (_u *SupportTicketUpdateOne) ClearMessages() *SupportTicketUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to SupportTicketMessage entities by IDs.
func (_u *SupportTicketUpdateOne) RemoveMessageIDs(ids ...int64) *SupportTicketUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to SupportTicketMessage entities.
func (_u *SupportTicketUpdateOne) RemoveMessages(v ...*SupportTicketMessage) *SupportTicketUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the SupportTicketUpdate builder.
func (_u *SupportTicketUpdateOne) Where(ps ...predicate.SupportTicket) *SupportTicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportTicketUpdateOne) Select(field string, fields ...string) *SupportTicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportTicket entity.
func (_u *SupportTicketUpdateOne) Save(ctx context.Context) (*SupportTicket, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) SaveX(ctx context.Context) *SupportTicket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportTicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportTicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportTicketUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportTicketUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := supportticket.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := supportticket.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supportticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := supportticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "SupportTicket.priority": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupportTicket.user"`)
	}
	return nil
}

func (_u *SupportTicketUpdateOne) sqlSave(ctx context.Context) (_node *SupportTicket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportticket.Table, supportticket.Columns, sqlgraph.NewFieldSpec(supportticket.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportTicket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportticket.FieldID)
		for _, f := range fields {
			if !supportticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(supportticket.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(supportticket.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportticket.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(supportticket.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(supportticket.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastUserMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastUserMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastUserMessageAtCleared() {
		_spec.ClearField(supportticket.FieldLastUserMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAdminMessageAt(); ok {
		_spec.SetField(supportticket.FieldLastAdminMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastAdminMessageAtCleared() {
		_spec.ClearField(supportticket.FieldLastAdminMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UserLastReadAt(); ok {
		_spec.SetField(supportticket.FieldUserLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.UserLastReadAtCleared() {
		_spec.ClearField(supportticket.FieldUserLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AdminLastReadAt(); ok {
		_spec.SetField(supportticket.FieldAdminLastReadAt, field.TypeTime, value)
	}
	if _u.mutation.AdminLastReadAtCleared() {
		_spec.ClearField(supportticket.FieldAdminLastReadAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(supportticket.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(supportticket.FieldClosedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.UserTable,
			Columns: []string{supportticket.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedAdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssignedAdminTable,
			Columns: []string{supportticket.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedAdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.AssignedAdminTable,
			Columns: []string{supportticket.AssignedAdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClosedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClosedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supportticket.ClosedByUserTable,
			Columns: []string{supportticket.ClosedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supportticket.MessagesTable,
			Columns: []string{supportticket.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supportticketmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupportTicket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
